import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Guitar LA - Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="heading">Desde Inicio</h1>

    <Link href="/nosotros">Ir a Nosotros</Link>

    </div>
  )
}
