import Head from 'next/head'
import Link from "next/link";

const nosotros = () => {
	return (
		<>
			<Head>
				<title>Guitar LA - Nosotros</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>Desde nosotros</div>

			<Link href="/">Inicio</Link>
		</>
	);
};

export default nosotros;
